apiVersion: v1
kind: ServiceAccount
metadata:
  name: nefi-agent
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: nefi-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nefi-agent
  labels:
    app.kubernetes.io/name: nefi-agent
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets", "deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nefi-agent
  labels:
    app.kubernetes.io/name: nefi-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nefi-agent
subjects:
  - kind: ServiceAccount
    name: nefi-agent
    namespace: {{ .Values.namespace }}
