apiVersion: v1
kind: Service
metadata:
  name: nefi-server
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: nefi-server
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - name: http
      port: {{ .Values.server.httpPort }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.server.grpcPort }}
      targetPort: grpc
      protocol: TCP
  selector:
    app.kubernetes.io/name: nefi-server
