apiVersion: v1
kind: Service
metadata:
  name: nefi-ui
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: nefi-ui
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: nefi-ui
